### ISSUE TITLE
bug: `UUID(word_uuid)` causes AivisSpeech-Engine startup failure

### ISSUE THREAD

**Issue by ConsetHP** [Aivis-Project/AivisSpeech-Engine#15]
## 不具合の内容

when I try to run file `run.exe` in Windows PowerShell, the program crashed after a few seconds and an error message showed up

### 現象・ログ

```
PS G:\s\AivisSpeech\AivisSpeech-Engine> ./run.exe
[2024/12/02 03:32:45] INFO:     AivisSpeech Engine version 1.1.0-dev
[2024/12/02 03:32:45] INFO:     Engine root directory: G:\s\AivisSpeech\AivisSpeech-Engine
[2024/12/02 03:32:45] INFO:     User data directory: G:\AppData\Roaming\AivisSpeech-Engine
[2024/12/02 03:32:45] INFO:     Models directory: G:\AppData\Roaming\AivisSpeech-Engine\Models
[2024/12/02 03:32:46] INFO:     Installed AIVM models:
[2024/12/02 03:32:46] INFO:     - Anneli (a59cb814-0083-4369-8542-f51a29e72af7)
[2024/12/02 03:32:46] INFO:     Using CPU for inference.
[2024/12/02 03:32:46] INFO:     Loading BERT model and tokenizer...
[2024/12/02 03:33:07] INFO:     BERT model and tokenizer loaded. (21.39s)
[2024/12/02 03:33:07] INFO:     Started server process [4004]
[2024/12/02 03:33:07] INFO:     Waiting for application startup.
[2024/12/02 03:33:07] INFO:     Application startup complete.
[2024/12/02 03:33:07] INFO:     Uvicorn running on http://localhost:10101 (Press CTRL+C to quit)
[2024/12/02 03:33:07] ERROR:    Failed to update user dictionary. (0.53s)
Traceback (most recent call last):
  File "voicevox_engine\user_dict\user_dict_manager.py", line 177, in update_dict
  File "voicevox_engine\user_dict\user_dict_manager.py", line 38, in func
  File "voicevox_engine\user_dict\user_dict_manager.py", line 247, in read_dict
  File "uuid.py", line 178, in __init__
ValueError: badly formed hexadecimal UUID string
Exception in thread Thread-1 (func):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "voicevox_engine\user_dict\user_dict_manager.py", line 38, in func
  File "voicevox_engine\user_dict\user_dict_manager.py", line 227, in update_dict
  File "voicevox_engine\user_dict\user_dict_manager.py", line 177, in update_dict
  File "voicevox_engine\user_dict\user_dict_manager.py", line 38, in func
  File "voicevox_engine\user_dict\user_dict_manager.py", line 247, in read_dict
  File "uuid.py", line 178, in __init__
ValueError: badly formed hexadecimal UUID string
```

### 再現手順

download [AivisSpeech-Engine-Windows-x64-1.1.0-dev.7z.001](https://github.com/Aivis-Project/AivisSpeech-Engine/releases/download/1.1.0-dev/AivisSpeech-Engine-Windows-x64-1.1.0-dev.7z.001) to a folder and extract it. Then right click on the folder and select `Open in Terminal`, run command `./run.exe`

### 期待動作

the program is supposed to run normally without any ERROR logs

## AivisSpeech Engine のバージョン

1.1.0-dev

## OS の種類 / バージョン

- [x] Windows 11 Pro 22H2 64bit (22621.2861)
- [ ] macOS
- [ ] Linux

## その他

I have also tried to use stable release [AivisSpeech-Engine-Windows-x64-1.0.0.7z.001](https://github.com/Aivis-Project/AivisSpeech-Engine/releases/download/1.0.0/AivisSpeech-Engine-Windows-x64-1.0.0.7z.001) but it turned out pretty much the same.

In addition, I've downloaded [AivisSpeech-Windows-x64-1.0.0.zip](https://github.com/Aivis-Project/AivisSpeech/releases/download/1.0.0/AivisSpeech-Windows-x64-1.0.0.zip) . But the engine wouldn’t start either, here's the log:

```
[2024/12/02 02:44:40] info: AivisSpeech version 1.1.0-dev
[2024/12/02 02:44:40] info: Migrating 1.1.0-dev to >=1.1 ...
[2024/12/02 02:44:40] info: Migrated 1.1.0-dev to >=1.1 successfully.
[2024/12/02 02:44:40] info: Starting 1 engine/s...
[2024/12/02 02:44:40] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3: Start launching
[2024/12/02 02:44:40] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3: Checking whether port 10101 is assignable...
[2024/12/02 02:44:40] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3: Starting process
[2024/12/02 02:44:40] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 mode: CPU
[2024/12/02 02:44:40] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 path: G:\s\AivisSpeech\AivisSpeech-Engine\run.exe
[2024/12/02 02:44:40] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 args: ["--host","127.0.0.1","--port","10101"]
[2024/12/02 02:44:40] info: Runtime information file has been updated. : G:\AppData\Roaming\AivisSpeech\runtime-info.json
[2024/12/02 02:44:41] info: [HotkeyManager] Editor changed to talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+n to 新規プロジェクト in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+n to 新規プロジェクト in song
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+s to プロジェクトを上書き保存 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+s to プロジェクトを上書き保存 in song
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+shift+s to プロジェクトを名前を付けて保存 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+shift+s to プロジェクトを名前を付けて保存 in song
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+o to プロジェクトを読み込む in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+o to プロジェクトを読み込む in song
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+z to 元に戻す in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+y to やり直す in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: shift+space to 連続再生/停止 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+e to 音声書き出し in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: e to 選択音声を書き出し in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+shift+e to 音声をつなげて書き出し in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: enter to テキスト欄にフォーカスを戻す in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+d to テキスト欄を複製 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: shift+enter to テキスト欄を追加 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: shift+delete to テキスト欄を削除 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: escape to テキスト欄からフォーカスを外す in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+a to すべて選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+1 to 1番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+2 to 2番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+3 to 3番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+4 to 4番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+5 to 5番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+6 to 6番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+7 to 7番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+8 to 8番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+9 to 9番目の話者を選択 in talk
[2024/12/02 02:44:41] info: [HotkeyManager] Bind: ctrl+0 to 10番目の話者を選択 in talk
[2024/12/02 02:44:42] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:42] INFO:     AivisSpeech Engine version 1.1.0-dev

[2024/12/02 02:44:42] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:42] INFO:     Engine root directory: G:\s\AivisSpeech\AivisSpeech-Engine
[2024/12/02 02:44:42] INFO:     User data directory: G:\AppData\Roaming\AivisSpeech-Engine

[2024/12/02 02:44:42] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:42] INFO:     Models directory: G:\AppData\Roaming\AivisSpeech-Engine\Models

[2024/12/02 02:44:42] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:42] INFO:     Installed AIVM models:

[2024/12/02 02:44:42] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:42] INFO:     - Anneli (a59cb814-0083-4369-8542-f51a29e72af7)
[2024/12/02 02:44:42] INFO:     Using CPU for inference.
[2024/12/02 02:44:42] INFO:     Loading BERT model and tokenizer...

[2024/12/02 02:44:44] info: [store/engine] Waiting engine 1b4a5014-d9fd-11ee-b97d-83c170a68ed3
[2024/12/02 02:44:44] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:44] INFO:     BERT model and tokenizer loaded. (2.28s)

[2024/12/02 02:44:44] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:44] INFO:     Started server process [20584]

[2024/12/02 02:44:44] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:44] INFO:     Waiting for application startup.
[2024/12/02 02:44:44] INFO:     Application startup complete.

[2024/12/02 02:44:44] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:44] INFO:     Uvicorn running on http://localhost:10101 (Press CTRL+C to quit)

[2024/12/02 02:44:44] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDOUT: [2024/12/02 02:44:44] INFO:     127.0.0.1:50308 - "GET /version HTTP/1.1" 200 OK

[2024/12/02 02:44:44] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDOUT: [2024/12/02 02:44:44] INFO:     127.0.0.1:50308 - "GET /engine_manifest HTTP/1.1" 200 OK

[2024/12/02 02:44:44] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDOUT: [2024/12/02 02:44:44] INFO:     127.0.0.1:50308 - "GET /version HTTP/1.1" 200 OK

[2024/12/02 02:44:44] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDOUT: [2024/12/02 02:44:44] INFO:     127.0.0.1:50309 - "GET /supported_devices HTTP/1.1" 200 OK

[2024/12/02 02:44:44] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDOUT: [2024/12/02 02:44:44] INFO:     127.0.0.1:50309 - "GET /speakers HTTP/1.1" 200 OK

[2024/12/02 02:44:44] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDOUT: [2024/12/02 02:44:44] INFO:     127.0.0.1:50309 - "GET /speaker_info?speaker_uuid=e756b8e4-b606-4e15-99b1-3f9c6a1b2317 HTTP/1.1" 200 OK

[2024/12/02 02:44:45] info: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDOUT: [2024/12/02 02:44:45] INFO:     127.0.0.1:50309 - "GET /user_dict HTTP/1.1" 500 Internal Server Error

[2024/12/02 02:44:45] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: [2024/12/02 02:44:45] ERROR:    Failed to update user dictionary. (0.70s)
Traceback (most recent call last):
  File "voicevox_engine\user_dict\user_dict_manager.py", line 177, in update_dict
  File "voicevox_engine\user_dict\user_dict_manager.py", line 38, in func
  File "voicevox_engine\user_dict\user_dict_manager.py", line 247, in read_dict
  File "uuid.py", line 178, in __init__
ValueError: badly formed hexadecimal UUID string

[2024/12/02 02:44:45] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR: Exception in thread Thread-1 (func):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "voicevox_engine\user_dict\user_dict_manager.py", line 38, in func

[2024/12/02 02:44:45] error: ENGINE 1b4a5014-d9fd-11ee-b97d-83c170a68ed3 STDERR:   File "voicevox_engine\user_dict\user_dict_manager.py", line 227, in update_dict
  File "voicevox_engine\user_dict\user_dict_manager.py", line 177, in update_dict
  File "voicevox_engine\user_dict\user_dict_manager.py", line 38, in func
  File "voicevox_engine\user_dict\user_dict_manager.py", line 247, in read_dict
  File "uuid.py", line 178, in __init__
ValueError: badly formed hexadecimal UUID string
```

Could anyone tell me whether there was any possible way to update the `user dictionary` mannually

**Comment by ConsetHP** [comment]
Managed to run the source code directly. After changed the code in line 99 from `"担々麺": create_word(WordProperty(`  into `"550e8400-e29b-41d4-a716-446655440000": create_word(WordProperty(` in file `voicevox_engine\user_dict\user_dict_manager.py`. The user dictionary updated successed. 

Then I copied the file `user.dic` in develop environment user data directory: `G:\AppData\Roaming\AivisSpeech-Engine-Dev` and pasted into normal user data directory `G:\AppData\Roaming\AivisSpeech-Engine`. Run `run.exe` again and everything worked fine
